language: node_js
sudo: false

matrix:
  include:
  - node_js: "0.10"
    env: V_REQUEST=2.76.0
  - node_js: "0.12"
    env: V_REQUEST=2.76.0
  - node_js: "iojs"
    env: V_REQUEST=2.76.0
  - node_js: "4"
    env: V_REQUEST=latest
  - node_js: "6"
    env: V_REQUEST=latest
  - node_js: "8"
    env: V_REQUEST=latest
  - node_js: "10"
    env: V_REQUEST=latest

before_install:
  - npm install tough-cookie
  - npm install request@$V_REQUEST

install: npm install
